# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jpngnbn
email: hello@jpanganiban.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts of a 20-something tech guy from the Philippines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jpanganiban.com" # the base hostname & protocol for your site
twitter_username: thejpanganiban
github_username:  thejpanganiban
body_classes: 

# Build settings
markdown: kramdown
